### ISSUE TITLE
Move slower

### ISSUE THREAD

**Issue by theoinkinator** [al3xkras/chess-com-bot-selenium#2]
Great release.

How do you make it move the pieces "slower" to appear more legitmate

**Comment by al3xkras** [comment]
Please check out the latest commit: b33d3945171a3835335868d62c2aee0b2447a416

**Comment by theoinkinator** [comment]
Thank you, works great. Still a bit glitchy trying to move pieces that aren't there or on the other side

**Comment by al3xkras** [comment]
The issue was fixed in the latest commit. Please, check, if the issue was addressed correctly.
