### ISSUE TITLE
Working in Ubuntu?

### ISSUE THREAD

**Issue by Pritam6569** [al3xkras/chess-com-bot-selenium#5]
Make it work if it doesn't pls

**Comment by al3xkras** [comment]
Any system that supports latest versions of Docker (Docker Desktop) and docker-selenium is supported. If installation is unsuccessful on your system, please describe the error in detail (ubuntu version / docker version / terminal output / docker logs etc).

**Comment by realpritam** [comment]
Ok working now so can you make it so it will automatically start a new match if one ends

**Comment by al3xkras** [comment]
> Ok working now so can you make it so it will automatically start a new match if one ends

Implemented in the latest commit
