### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by theoinkinator** [al3xkras/chess-com-bot-selenium#6]
![c94e9d4a43de4756aceca5a681576ee7](https://github.com/al3xkras/chess-com-bot-selenium/assets/122758041/3d26aba0-3221-4e74-a02e-6e7bc97a6310)

**Comment by al3xkras** [comment]
![image](https://github.com/al3xkras/chess-com-bot-selenium/assets/62184786/d39b808c-6c18-4693-935b-79a26b421424)

It seems like you are using a Stockfish version marked as "pre-release". This version might be incompatible with the official python bindings

I would consider using the latest stable release (Stockfish 16.1), which should solve the issue:

https://github.com/official-stockfish/Stockfish/releases/tag/sf_16.1

![image](https://github.com/al3xkras/chess-com-bot-selenium/assets/62184786/d8f60f30-a7a0-4b56-b596-2a52824715a2)

**Comment by theoinkinator** [comment]
works, thank you
