### ISSUE TITLE
Errors, goes away after finding new match

### ISSUE THREAD

**Issue by theoinkinator** [al3xkras/chess-com-bot-selenium#7]
![daddbfe1f0e9779a1e47cd8c81bf5911](https://github.com/al3xkras/chess-com-bot-selenium/assets/122758041/31717a92-eaae-46d1-b084-9b7ceddf2913)

**Comment by al3xkras** [comment]
Could you provide a commit reference in which this error was reproduced?

**Comment by theoinkinator** [comment]
Idk how to do that sorry D:

**Comment by al3xkras** [comment]
In other words, I was unable to reproduce this error in the latest commit.

**Comment by theoinkinator** [comment]
Ah, okay. It happens when I leave it on for long periods of times, rarely though, I tried reproducing it myself but to no avail. Unfortunate!
